name: Deploy
# this file is for destroying resources
on:
  push:
    branches:
      - main
  workflow_dispatch:
    inputs:
      action:
        description: 'Deploy the resources'
        required: true
        default: 'Deploy'

jobs:
  destroy:
    runs-on: ubuntu-latest
    environment: production
    steps:
    - name: Checkout repo
      uses: actions/checkout@v2

    - name: Set up Azure credentials
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}

    - name: Set up Terraform
      uses: hashicorp/setup-terraform@v1
      with:
        terraform_version: '1.0.0'

    - name: Terraform Init
      run: terraform init

    - name: Terraform Plan
      run: terraform Plan -var-file=cvnet.tfvars -auto-approve

    - name: Terraform Apply
      run: terraform Apply -var-file=cvnet.tfvars -auto-approve

