name: Azure Terraform Deployment

on:
  workflow_dispatch:
  # push:
  #   branches:
  #     - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.TERRAAZURE }}

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v1

      - name: Terraform Init
        env:
          ARM_CLIENT_ID: ${{ fromJson(secrets.TERRAAZURE).clientId }}
          ARM_CLIENT_SECRET: ${{ fromJson(secrets.TERRAAZURE).clientSecret }}
          ARM_TENANT_ID: ${{ fromJson(secrets.TERRAAZURE).tenantId }}
          ARM_SUBSCRIPTION_ID: ${{ fromJson(secrets.TERRAAZURE).subscriptionId }}
        run: terraform init

      - name: Terraform Plan
        env:
          ARM_CLIENT_ID: ${{ fromJson(secrets.TERRAAZURE).clientId }}
          ARM_CLIENT_SECRET: ${{ fromJson(secrets.TERRAAZURE).clientSecret }}
          ARM_TENANT_ID: ${{ fromJson(secrets.TERRAAZURE).tenantId }}
          ARM_SUBSCRIPTION_ID: ${{ fromJson(secrets.TERRAAZURE).subscriptionId }}
        run: terraform plan

      - name: Terraform Apply
        env:
          ARM_CLIENT_ID: ${{ fromJson(secrets.TERRAAZURE).clientId }}
          ARM_CLIENT_SECRET: ${{ fromJson(secrets.TERRAAZURE).clientSecret }}
          ARM_TENANT_ID: ${{ fromJson(secrets.TERRAAZURE).tenantId }}
          ARM_SUBSCRIPTION_ID: ${{ fromJson(secrets.TERRAAZURE).subscriptionId }}
        run: terraform apply -auto-approve
