name: Azure Terraform Deployment

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Azure Login
        id: azure_login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.TERRAAZURE }}

      - name: Set up Terraform
        run: |
          echo "Setting up Terraform"
          curl -LO https://releases.hashicorp.com/terraform/1.1.6/terraform_1.1.6_linux_amd64.zip
          unzip terraform_1.1.6_linux_amd64.zip
          sudo mv terraform /usr/local/bin/

      - name: Configure Azure credentials for Terraform
        run: |
          echo "Configuring Azure credentials for Terraform"
          AZURE_CREDENTIALS=${{ secrets.TERRAAZURE }}
          echo $AZURE_CREDENTIALS | jq -r '.clientId' | xargs -I {} echo "export ARM_CLIENT_ID={}" >> $GITHUB_ENV
          echo $AZURE_CREDENTIALS | jq -r '.clientSecret' | xargs -I {} echo "export ARM_CLIENT_SECRET={}" >> $GITHUB_ENV
          echo $AZURE_CREDENTIALS | jq -r '.tenantId' | xargs -I {} echo "export ARM_TENANT_ID={}" >> $GITHUB_ENV
          echo $AZURE_CREDENTIALS | jq -r '.subscriptionId' | xargs -I {} echo "export ARM_SUBSCRIPTION_ID={}" >> $GITHUB_ENV

      - name: Terraform Init
        run: terraform init

      - name: Terraform Plan
        run: terraform plan

      - name: Terraform Apply
        run: terraform apply -auto-approve
